kind: pipeline
name: Drone

steps:
 - name: compile
   image: starlight2834/ci_docker:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
      - apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex bison
      - git config --global user.name "me"
      - git config --global user.email "me@gmail.com"
      - git config --global color.ui false
      - git clone https://github.com/JamieHoSzeYui/build build/
      - cd build
      - bash complex.sh lancelot-oc
